Added missing files and c++98 content-filtering
rticommunity/rticonnextdds-getting-started pull request #34
Opened 2020-09-28 00:10 UTC by rosemwahlin

Added files that were missing from the last commit, fixing minor bugs, added:
- CMake and application.hpp files missing from C++11
- C++98 files
- Scripts to run all applications at once (note Windows is still missing)
- Updates to CMake scripts to copy the run scripts

2020-09-28 10:03 UTC, fgaranda requested changes

2020-09-28 10:03 UTC, fgaranda commented on 6_content_filters/c++11/start_all_linux.sh
> +    gnome-terminal -x bash -c "./$executable_name -k COCOA_BUTTER_CONTROLLER $*"
This is only going to work if you have gnome-terminal installed, which won't be the case if you're using Plasma.

2020-09-28 10:03 UTC, fgaranda commented on 6_content_filters/c++11/start_all_macos.sh
> +    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
In macOs you use DYLD_LIBRARY_PATH, but does it work anymore or you have to disable SIP?

Why don't you do some checks at the begining for the OS you're running on and then you decide what the right terminal and commands are? It'd be best to have only a  single .sh script that supports everything.

2020-09-28 10:16 UTC, fgaranda requested changes

2020-09-28 10:16 UTC, fgaranda commented on 6_content_filters/c++98/application.h
> +typedef void* (*ThreadFunction)(void *);
You could separate this functionality into different files, it's getting a bit cluttered.

2020-10-04 22:10 UTC, rosemwahlin commented on 6_content_filters/c++11/start_all_macos.sh
> +    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
I can't read SIP as anything other than shelter-in-place any more :-D 

I combined the scripts, but have not been able to test with Konsole, yet.

2020-10-05 21:14 UTC, rosemwahlin commented on 6_content_filters/c++11/start_all_linux.sh
> +    gnome-terminal -x bash -c "./$executable_name -k COCOA_BUTTER_CONTROLLER $*"
Updated.

2020-10-06 20:25 UTC, rosemwahlin commented on 6_content_filters/c++98/application.h
> +typedef void* (*ThreadFunction)(void *);
I moved the printing to a new file.

2020-10-12 21:07 UTC, alexcamposruiz requested changes
I'm skipping the XML Qos files and cmake files.

2020-10-12 21:07 UTC, alexcamposruiz commented on 6_content_filters/c++98/ingredient_application.cxx
> +        std::cerr << "take error " << retcode << std::endl;
With `DDS_RETCODE_NO_DATA` you should just exit without printing an error

2020-10-12 21:07 UTC, alexcamposruiz commented on 6_content_filters/c++98/ingredient_application.cxx
> +            continue;
This `else continue` doesn't do anything. I would do this instead:

```
if (!valid_data) {
    // received ...
   continue;
}

std::cout << ...
...
```

2020-10-13 00:40 UTC, rosemwahlin commented on 6_content_filters/c++98/ingredient_application.cxx
> +        std::cerr << "take error " << retcode << std::endl;
This doesn't print an error if there is no data, but it doesn't return immediately – added a return.

2020-10-13 15:40 UTC, alexcamposruiz commented on 6_content_filters/c++98/ingredient_application.cxx
> +        std::cerr << "take error " << retcode << std::endl;
oh you're right. I guess not returning immediately is not a bug in and of itself because you won't enter the loop, and return_loan won't do anything...

2020-10-13 15:41 UTC, alexcamposruiz approved these changes

2020-10-14 08:16 UTC, fgaranda approved these changes

2020-10-14 23:46 UTC, merged